#!/bin/bash
set -e

cd /opt/scraper/src
/usr/local/bin/python -m scraper
status=$?

if [ -n "${HEALTHCHECK_ID}" ]; then
  wget https://hc-ping.com/${HEALTHCHECK_ID}/$status -T 10 -t 5 -O /dev/null
fi
